# Generated by Django 4.2.3 on 2023-07-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageField',
            new_name='Message',
        ),
    ]
